//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ON163.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_ord
    {
        public string имя { get; set; }
        public string фамилия { get; set; }
        public string отчество { get; set; }
        public string телефон { get; set; }
        public System.DateTime дата_рождения { get; set; }
    }
}
